name: DemoTranspiler
description: ''
version: 0.0.1
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demotranspiler
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-09 15:26:32'
pipelines:
  pipelines/real_graph1:
    name: real_graph_raw_import
    description: null
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-09 16:44:47'
    datasets:
      inputs: []
      outputs:
      - datasets/Output_File
    subgraphs: []
    dependencies: {}
  pipelines/real_graph2:
    name: real_graph_fixed
    description: null
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-09 19:22:18'
    datasets:
      inputs:
      - datasets/hello_world_hw_customers
      - datasets/hello_world_hw_orders
      outputs:
      - datasets/Output_File
    subgraphs: []
    dependencies: {}
datasets:
  datasets/Output_File:
    name: Output_File
    description: 'Dataset for componentName: Output_File'
    author: bobw@prophecy.io
    createdAt: '2024-08-09 16:44:47'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-09 16:44:47'
  datasets/hello_world_hw_orders:
    name: hello_world_hw_orders
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-09 19:25:14'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-09 19:25:14'
  datasets/hello_world_hw_customers:
    name: hello_world_hw_customers
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-08-09 19:25:19'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-08-09 19:25:19'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-09 15:26:32'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-08-09T15:26:32.778624Z'
  name: plibMaven
  version: 8.0.29
  id: '807008467'
  createdAt: '2024-08-09T15:26:32.778624Z'
  type: plibMaven
- modifiedAt: '2024-08-09T15:26:32.778624Z'
  name: plibPypi
  version: 1.9.9
  id: '1528918909'
  createdAt: '2024-08-09T15:26:32.778624Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.26
    isDefault: true
    author: null
    createdAt: '2024-08-12 12:54:15'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-09 13:03:16'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
