from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def AlteryxSelect_223(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("DeliveryDueDate"), 
        col("ManufacturingOrderId"), 
        col("QTYProcessedPO"), 
        col("Packaging"), 
        col("FiberType"), 
        col("RunHours"), 
        col("Lead"), 
        col("WireGauge"), 
        col("Plant"), 
        col("ScrewRetention"), 
        col("DeadChannels"), 
        col("LeadFree"), 
        col("ScrapHours"), 
        col("CompletedHours"), 
        col("SpaceOption"), 
        col("IsProcessCompleted"), 
        col("Ends"), 
        col("LineNumber"), 
        col("Polarized"), 
        col("WorkCenterNumber"), 
        col("PartNumber").alias("Part Number"), 
        col("Process"), 
        col("Latching"), 
        col("Entry"), 
        col("Shield"), 
        col("QuantityRequired"), 
        col("ReverseConnector"), 
        col("ReceivingChannels"), 
        col("QTYProcessedWC"), 
        col("QTYProcessedTotal").alias("QTYproducedTotal"), 
        col("WiringOption"), 
        col("Direction"), 
        col("Country"), 
        col("SurfaceMount"), 
        col("DaisyChain"), 
        col("Pad"), 
        col("OpticEnd"), 
        col("Key"), 
        col("LikePartNumber").alias("Like Part"), 
        col("Retention"), 
        col("TransmittingChannels"), 
        col("ReverseWire"), 
        col("Engines"), 
        col("MiddleReverse"), 
        col("Positions"), 
        col("SetupHours"), 
        col("StrainRelief"), 
        col("WorkCenter"), 
        col("PowerPins"), 
        col("MechanicalSample"), 
        col("DifferentialPair"), 
        col("ManufacturingDueDate"), 
        col("Pitch"), 
        col("Alignment"), 
        col("Routing"), 
        col("Length"), 
        col("ProcessOrderId"), 
        col("ReviewBoard"), 
        col("OutsideReverse"), 
        col("CableOptions"), 
        col("Mount"), 
        col("Notch"), 
        col("Facility"), 
        col("OpticsType"), 
        col("Breakout"), 
        col("Rows"), 
        col("ScrapQuantity"), 
        col("CableRetention"), 
        col("OrderNumber"), 
        col("ReportingSeries").alias("ReportingSeriesCode"), 
        col("IsCustomerOrder"), 
        col("StepNumber"), 
        col("ReverseNotch"), 
        col("Speed"), 
        col("Gender"), 
        col("Plating")
    )
