from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def AlteryxSelect_254(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("DifferentialPair"), 
        col("WiringOption"), 
        col("FiberType"), 
        col("OpticEnd"), 
        col("CableRetention"), 
        col("Pitch"), 
        col("Notch"), 
        col("PowerPins"), 
        col("Breakout"), 
        col("Gender"), 
        col("StrainRelief"), 
        col("WireGauge"), 
        col("`Automation Level`").alias("Automation Level"), 
        col("`Average Hourly Output`").alias("Average Hourly Output"), 
        col("CompletedHours"), 
        col("Country"), 
        col("`Daily Production Hours`").alias("Daily Production Hours"), 
        col("`Days per Month`").alias("Days per Month"), 
        col("`Days per Quarter`").alias("Days per Quarter"), 
        col("DeliveryDueDate"), 
        col("Facility"), 
        col("`Finished Good Part`").alias("Finished Good Part"), 
        col("IsCustomerOrder"), 
        col("IsProcessCompleted"), 
        col("`Like Part`").alias("Like Part"), 
        col("LineNumber"), 
        col("`Machine Group ID`").alias("Machine Group ID"), 
        col("`Machine Group Notes`").alias("Machine Group Notes"), 
        col("`Machine Type`").alias("Machine Type"), 
        col("ManufacturingDueDate"), 
        col("ManufacturingOrderId"), 
        col("OrderNumber"), 
        col("`Part Number`").alias("Part Number"), 
        col("`Part Wildcard`").alias("Part Wildcard"), 
        col("Pipeline"), 
        col("Plant"), 
        col("`Plant Process Code`").alias("Plant Process Code"), 
        col("Process"), 
        col("ProcessOrderId"), 
        col("`Projected Annual Growth`").alias("Projected Annual Growth"), 
        col("QTYProcessedPO"), 
        col("QTYProcessedWC"), 
        col("QTYproducedTotal"), 
        col("QuantityRequired"), 
        col("ReportingSeriesCode"), 
        col("ReviewBoard"), 
        col("Routing"), 
        col("RunHours"), 
        col("ScrapHours"), 
        col("ScrapQuantity"), 
        col("SetupHours"), 
        col("StepNumber"), 
        col("`Target Utilization`").alias("Target Utilization"), 
        col("`Tooling Set`").alias("Tooling Set"), 
        col("WorkCenter"), 
        col("WorkCenterNumber"), 
        col("`Facility Machine Group Name`").alias("Facility Machine Group Name"), 
        col("Mount"), 
        col("Direction"), 
        col("Lead"), 
        col("Rows"), 
        col("Positions"), 
        col("Plating"), 
        col("Packaging"), 
        col("Pad"), 
        col("Alignment"), 
        col("Retention"), 
        col("Key"), 
        col("Latching"), 
        col("Entry"), 
        col("LeadFree"), 
        col("Polarized"), 
        col("Ends"), 
        col("ReverseWire"), 
        col("DaisyChain"), 
        col("ReverseConnector"), 
        col("MiddleReverse"), 
        col("OutsideReverse"), 
        col("ReverseNotch"), 
        col("ScrewRetention"), 
        col("Length"), 
        col("CableOptions"), 
        col("Shield"), 
        col("SpaceOption"), 
        col("SurfaceMount"), 
        col("Engines"), 
        col("TransmittingChannels"), 
        col("ReceivingChannels"), 
        col("DeadChannels"), 
        col("Speed"), 
        col("MechanicalSample"), 
        col("OpticsType")
    )
