from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def AlteryxSelect_256(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("DifferentialPair"), 
        col("WiringOption"), 
        col("FiberType"), 
        col("OpticEnd"), 
        col("CableRetention"), 
        col("Pitch"), 
        col("Notch"), 
        col("PowerPins"), 
        col("Breakout"), 
        col("Gender"), 
        col("StrainRelief"), 
        col("WireGauge"), 
        col("`Finished Good Part`").alias("Finished Good Part"), 
        col("`Tooling Set`").alias("Tooling Set"), 
        col("ProcessOrderId"), 
        col("LineNumber"), 
        col("StepNumber"), 
        col("RunHours"), 
        col("SetupHours"), 
        col("IsProcessCompleted"), 
        col("ManufacturingDueDate"), 
        col("DeliveryDueDate"), 
        col("CompletedHours"), 
        col("ScrapHours"), 
        col("QTYproducedTotal"), 
        col("ScrapQuantity"), 
        col("QTYProcessedWC"), 
        col("QTYProcessedPO"), 
        col("ManufacturingOrderId"), 
        col("QuantityRequired"), 
        col("Facility"), 
        col("Process"), 
        col("ReportingSeriesCode"), 
        col("`Like Part`").alias("Like Part"), 
        col("Routing"), 
        col("IsCustomerOrder"), 
        col("Plant"), 
        col("ReviewBoard"), 
        col("Country"), 
        col("WorkCenter"), 
        col("`Part Number`").alias("Part Number"), 
        col("WorkCenterNumber"), 
        col("OrderNumber"), 
        col("Mount"), 
        col("Direction"), 
        col("Lead"), 
        col("Rows"), 
        col("Positions"), 
        col("Plating"), 
        col("Packaging"), 
        col("Pad"), 
        col("Alignment"), 
        col("Retention"), 
        col("Key"), 
        col("Latching"), 
        col("Entry"), 
        col("LeadFree"), 
        col("Polarized"), 
        col("Ends"), 
        col("ReverseWire"), 
        col("DaisyChain"), 
        col("ReverseConnector"), 
        col("MiddleReverse"), 
        col("OutsideReverse"), 
        col("ReverseNotch"), 
        col("ScrewRetention"), 
        col("Length"), 
        col("CableOptions"), 
        col("Shield"), 
        col("SpaceOption"), 
        col("SurfaceMount"), 
        col("Engines"), 
        col("TransmittingChannels"), 
        col("ReceivingChannels"), 
        col("DeadChannels"), 
        col("Speed"), 
        col("MechanicalSample"), 
        col("OpticsType")
    )
