from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def AlteryxSelect_258(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("Lead"), 
        col("DaisyChain"), 
        col("Country"), 
        col("ScrewRetention"), 
        col("Shield"), 
        col("Process"), 
        col("DifferentialPair"), 
        col("StepNumber"), 
        col("Facility"), 
        col("Retention"), 
        col("ReportingSeriesCode"), 
        col("Routing"), 
        col("DeadChannels"), 
        col("ReverseNotch"), 
        col("Rows"), 
        col("WiringOption"), 
        col("SurfaceMount"), 
        col("IsCustomerOrder"), 
        col("Entry"), 
        col("QTYProcessedPO"), 
        col("WorkCenterNumber"), 
        col("ReviewBoard"), 
        col("RunHours"), 
        col("Plant"), 
        col("FiberType"), 
        col("Ends"), 
        col("CompletedHours"), 
        col("QTYproducedTotal"), 
        col("IsProcessCompleted"), 
        col("OutsideReverse"), 
        col("MechanicalSample"), 
        col("Length"), 
        col("Packaging"), 
        col("ReverseWire"), 
        col("OpticEnd"), 
        col("`Like Part`").alias("Like Part"), 
        col("Alignment"), 
        col("CableRetention"), 
        col("Direction"), 
        col("WorkCenter"), 
        col("ScrapHours"), 
        col("OrderNumber"), 
        col("ReverseConnector"), 
        col("Pitch"), 
        col("Positions"), 
        col("Latching"), 
        col("CableOptions"), 
        col("ManufacturingOrderId"), 
        col("LeadFree"), 
        col("QTYProcessedWC"), 
        col("Speed"), 
        col("Notch"), 
        col("SetupHours"), 
        col("Engines"), 
        col("PowerPins"), 
        col("QuantityRequired"), 
        col("LineNumber"), 
        col("ReceivingChannels"), 
        col("`Part Number`").alias("Part Number"), 
        col("MiddleReverse"), 
        col("TransmittingChannels"), 
        col("Breakout"), 
        col("Pad"), 
        col("OpticsType"), 
        col("Gender"), 
        col("`Finished Good Part`").alias("Finished Good Part"), 
        col("ManufacturingDueDate"), 
        col("`Tooling Set`").alias("Tooling Set"), 
        col("ProcessOrderId"), 
        col("Key"), 
        col("SpaceOption"), 
        col("StrainRelief"), 
        col("WireGauge"), 
        col("Plating"), 
        col("Polarized"), 
        col("Mount"), 
        col("ScrapQuantity"), 
        col("DeliveryDueDate")
    )
