from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def DynamicRename_282(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("`Work Center Number`").alias("Work Center Number"), 
        col("`Days per Month`").alias("Days per Month"), 
        col("`Part Wildcard`").alias("Part Wildcard"), 
        col("`Manufacturing Order Id`").alias("Manufacturing Order Id"), 
        col("`Shipping On Time Status`").alias("Shipping On Time Status"), 
        col("`Average Hourly Output`").alias("Average Hourly Output"), 
        col("`Machine Group Notes`").alias("Machine Group Notes"), 
        col("`Scrap Quantity`").alias("Scrap Quantity"), 
        col("`Daily Production Hours`").alias("Daily Production Hours"), 
        col("`Facility Machine Group Name`").alias("Facility Machine Group Name"), 
        col("`Manufacturing Due Date`").alias("Manufacturing Due Date"), 
        col("SetupHours"), 
        col("`Manufacturing On Time Status`").alias("Manufacturing On Time Status"), 
        col("QuantityRequired"), 
        col("`Is Customer Order`").alias("Is Customer Order"), 
        col("`Reporting Series`").alias("Reporting Series"), 
        col("`Days per Quarter`").alias("Days per Quarter"), 
        col("`Process Order Quantity Processed`").alias("Process Order Quantity Processed"), 
        col("`Machine Type`").alias("Machine Type"), 
        col("`Deliver To`").alias("Deliver To"), 
        col("`Like Part`").alias("Like Part"), 
        col("Pipeline"), 
        col("Plant"), 
        col("WorkCenter"), 
        col("`Part Number`").alias("Part Number"), 
        col("`Projected Annual Growth`").alias("Projected Annual Growth"), 
        col("ReviewBoard"), 
        col("`Reschedule Reason`").alias("Reschedule Reason"), 
        col("DeliveryDueDate"), 
        col("`Automation Level`").alias("Automation Level"), 
        col("`Machine Group ID`").alias("Machine Group ID"), 
        col("OrderNumber"), 
        col("LineNumber"), 
        col("`Reschedule Notes`").alias("Reschedule Notes"), 
        col("`Target Utilization`").alias("Target Utilization"), 
        col("`Is Scarlet`").alias("Is Scarlet"), 
        col("`Scrap Hours`").alias("Scrap Hours"), 
        col("`Completed Hours`").alias("Completed Hours"), 
        col("`Run Hours`").alias("Run Hours"), 
        col("Process"), 
        col("DateRefreshed"), 
        col("`Date Entered`").alias("Date Entered"), 
        col("`Tooling BOM Part Number`").alias("Tooling BOM Part Number"), 
        col("`Tooling Set`").alias("Tooling Set"), 
        col("`Process Plant Code`").alias("Process Plant Code"), 
        col("Mount").alias("spo.Mount"), 
        col("Direction").alias("spo.Direction"), 
        col("Lead").alias("spo.Lead"), 
        col("Rows").alias("spo.Rows"), 
        col("Positions").alias("spo.Positions"), 
        col("Plating").alias("spo.Plating"), 
        col("Packaging").alias("spo.Packaging"), 
        col("Pad").alias("spo.Pad"), 
        col("Alignment").alias("spo.Alignment"), 
        col("Retention").alias("spo.Retention"), 
        col("Key").alias("spo.Key"), 
        col("Latching").alias("spo.Latching"), 
        col("Entry").alias("spo.Entry"), 
        col("LeadFree").alias("spo.LeadFree"), 
        col("Polarized").alias("spo.Polarized"), 
        col("Ends").alias("spo.Ends"), 
        col("ReverseWire").alias("spo.ReverseWire"), 
        col("DaisyChain").alias("spo.DaisyChain"), 
        col("ReverseConnector").alias("spo.ReverseConnector"), 
        col("MiddleReverse").alias("spo.MiddleReverse"), 
        col("OutsideReverse").alias("spo.OutsideReverse"), 
        col("ReverseNotch").alias("spo.ReverseNotch"), 
        col("ScrewRetention").alias("spo.ScrewRetention"), 
        col("Length").alias("spo.Length"), 
        col("CableOptions").alias("spo.CableOptions"), 
        col("Shield").alias("spo.Shield"), 
        col("SpaceOption").alias("spo.SpaceOption"), 
        col("SurfaceMount").alias("spo.SurfaceMount"), 
        col("Engines").alias("spo.Engines"), 
        col("TransmittingChannels").alias("spo.TransmittingChannels"), 
        col("ReceivingChannels").alias("spo.ReceivingChannels"), 
        col("DeadChannels").alias("spo.DeadChannels"), 
        col("Speed").alias("spo.Speed"), 
        col("MechanicalSample").alias("spo.MechanicalSample"), 
        col("OpticsType").alias("spo.OpticsType"), 
        col("Breakout").alias("spo.Breakout"), 
        col("CableRetention").alias("spo.CableRetention"), 
        col("DifferentialPair").alias("spo.DifferentialPair"), 
        col("FiberType").alias("spo.FiberType"), 
        col("Gender").alias("spo.Gender"), 
        col("Notch").alias("spo.Notch"), 
        col("OpticEnd").alias("spo.OpticEnd"), 
        col("PowerPins").alias("spo.PowerPins"), 
        col("StrainRelief").alias("spo.StrainRelief"), 
        col("WireGauge").alias("spo.WireGauge"), 
        col("WiringOption").alias("spo.WiringOption"), 
        col("Pitch").alias("spo.Pitch")
    )
